spring.application.name=Regalis
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:regalis_db}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
# show operations sorted
springdoc.swagger-ui.operationsSorter=alpha
# enable try it out (default true)
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
regalis.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#1 DAY
regalis.app.jwtExpirationMs=86400000